name: osaa-mvp

x-common-config: &common-config
  build: .
  env_file: .env
  volumes:
    - ./datalake:/app/datalake
    - ./sqlMesh:/app/sqlMesh
  environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - AWS_ROLE_ARN=${AWS_ROLE_ARN}
    - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    - TARGET=${TARGET}
    - USERNAME=${USERNAME}
    - DB_PATH=/app/sqlMesh/unosaa_data_pipeline.db

services:
  pipeline:
    <<: *common-config
    container_name: osaa-mvp-main
    environment:
      - GATEWAY=${GATEWAY:-local}
    profiles:
      - default

  ui:
    <<: *common-config
    container_name: osaa-mvp-ui
    working_dir: /app/sqlMesh
    command: ["ui"]
    environment:
      - GATEWAY=local
    ports:
      - "${UI_PORT:-8080}:${UI_PORT:-8080}"
    profiles:
      - ui
