name: Daily ETL Job

on:
  schedule:
    # Run at 9:00 AM EST every day
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest
    env:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      TARGET: prod
      USERNAME: ${{ secrets.USERNAME || 'osaa-mvp-user' }}
      GATEWAY: local
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker ETL Command
        env:
          TARGET: prod
          GATEWAY: local
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          USERNAME: ${{ secrets.USERNAME || 'osaa-mvp-user' }}
        run: |
          docker run --rm \
            -e TARGET=$TARGET \
            -e GATEWAY=$GATEWAY \
            -e AWS_ROLE_ARN=$AWS_ROLE_ARN \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
            -e S3_BUCKET_NAME=$S3_BUCKET_NAME \
            -e USERNAME=$USERNAME \
            ghcr.io/un-osaa/osaa-mvp:latest \
            etl prod 